### ISSUE TITLE
`tauri::generate_context!()` error: OUT_DIR env var is not set

### ISSUE THREAD

**Issue by ctaggart** [tauri-apps/tauri-egui#12]
I've been trying to get started with tauri-egui 0.1.0 and I have something wrong in my setup. When I compile, I get this error:

```
error: OUT_DIR env var is not set, do you have a build script?
  --> src\main.rs:16:16
   |
16 |         .build(tauri::generate_context!())
   |                ^^^^^^^^^^^^^^^^^^^^^^^^^
 ```
 
I created this minimal project to reproduce:
https://github.com/ctaggart/tauri-egui-basic/

**Comment by amrbashir** [comment]
your project is missing a `build.rs` script with the following content:
```rs
fn main() {
  tauri_build::build()
}
```

**Comment by amrbashir** [comment]
you also need to add `tauri-build` to your `build-dependencies` in `Cargo.toml`
