### ISSUE TITLE
Compilation error egui 

### ISSUE THREAD

**Issue by DevPlus31** [tauri-apps/tauri-egui#15]
I tried reproducing the article below, unfortunately  I am getting compilation errors (98 errors)
https://tauri.app/blog/2022/09/19/tauri-egui-0-1/ 

Since the log is quite big I've included a file with build result.

[debug.txt](https://github.com/tauri-apps/tauri-egui/files/10045218/debug.txt)

Thank you.

**Comment by amrbashir** [comment]
A new version has been released, please try again. don't forget to run `cargo update` inside the project.
